Controllers/BrokerController.cs
using Microsoft.AspNetCore.Mvc;
using agendaEFD.Data;
using agendaEFD.Models;

namespace agendaEFD.Controllers
{
    public class BrokerController : Controller
    {
        private readonly agendaContext _db;

        public BrokerController(agendaContext db)
        {
            _db = db;
        }
        /*
        public IActionResult Index()
        {
            IEnumerable<Broker> Brokers = _db.Brokers;
            return View(Brokers);
        } */

        public IActionResult Index(string? searchString)
        {
            IEnumerable<Broker> Brokers = _db.Brokers;

            if (!String.IsNullOrEmpty(searchString))
            {
                var brokers = from c in _db.Brokers select c;
                brokers = brokers.Where(s => s.Lastname!.Contains(searchString) || s.Firstname.Contains(searchString));
                return View(brokers.ToList());
            }

            return View(Brokers);
        }

        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Broker broker)
        {
            if (broker.Firstname == broker.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }

            if (ModelState.IsValid)
            {

                _db.Brokers.Add(broker);
                _db.SaveChanges();

                TempData["success"] = "Le courtier a bien été ajouté";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id) 
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            return View(broker);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        // on peut aussi mettre "int Id" dans les parametres
        // et ca récupère l'id depuis le form sans avoir besoin d'ajouter un hidden dans le form
        public IActionResult Edit(Broker broker) 
        {
            if (broker.Firstname == broker.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }

            // broker.IdBroker = id;

            if (ModelState.IsValid)
            {


                _db.Brokers.Update(broker);
                _db.SaveChanges();

                TempData["success"] = "Le courtier a bien été modifié";

                return RedirectToAction("Index");
            }


            return View();

        }

        public IActionResult Profil(int? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            ViewBag.BrokerId = id;
            return View(broker);
        }

        // pour aller sur la view Delete 
        public IActionResult Delete(int? id)
        {
            // si j'ai pas d'id je retourne a la liste des articles
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            return View(broker);
        }

        [HttpPost]
        public IActionResult Delete(Broker broker)
        {
            foreach (var n in _db.Appointments.Where(brok => brok.IdBroker == broker.IdBroker).ToArray())
                _db.Appointments.Remove(n);
            /*
            var app = from a in _db.Appointments.ToList() where a.IdBroker == broker.IdBroker select a;
            if(app.Count() != 0) // ou app.Any()
            {
                _db.Appointments.RemoveRange(app);
            }
            */

            _db.Brokers.Remove(broker);
            
            _db.SaveChanges();

            TempData["success"] = "Le courtier a bien été supprimé";

            return RedirectToAction("Index");
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using agendaEFD.Data;
using agendaEFD.Models;

namespace agendaEFD.Controllers
{
    public class CustomerController : Controller
    {
        private readonly agendaContext _db;

        public CustomerController(agendaContext db)
        {
            _db = db;
        }
        /*
        public IActionResult Index()
        {
            IEnumerable<Customer> Customers = _db.Customers; */

            /* J'aurai pu faire ca aussi:
            var queryCustomers = _db.Customers.FromSqlRaw("select * from customers order by lastName").ToList();
            ViewBag.Customers = queryCustomers; */
            /*
            return View(Customers);
        }
        */

        public IActionResult Index(string? searchString)
        {
            IEnumerable<Customer> Customers = _db.Customers;

            if (!String.IsNullOrEmpty(searchString))
            {
                var customers = from c in _db.Customers select c;
                customers = customers.Where(s => s.Lastname!.Contains(searchString) || s.Firstname.Contains(searchString));
                return View(customers.ToList());
            }

            return View(Customers);
        }

        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Customer customer)
        {
            if (customer.Firstname == customer.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }

            if (ModelState.IsValid)
            {

                _db.Customers.Add(customer);
                _db.SaveChanges();

                TempData["success"] = "Le client a bien été ajouté";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var customer = _db.Customers.Find(id);

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Customer cust)
        {
            if (cust.Firstname == cust.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }



            if (ModelState.IsValid)
            {

                _db.Customers.Update(cust);
                _db.SaveChanges();

                TempData["success"] = "Le client a bien été modifié";

                return RedirectToAction("Index");
                // ViewData["dump"] = cust;

                // return View();
            }


            return View();

        }

        public IActionResult Profil(int? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var customer = _db.Customers.Find(id);

            if (customer == null)
            {
                return NotFound();
            }

            ViewBag.CustomerId = id;
            return View(customer);
        }

        // pour aller sur la view Delete 
        public IActionResult Delete(int? id)
        {
            // si j'ai pas d'id je retourne a la liste des articles
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var customer = _db.Customers.Find(id);

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        [HttpPost]
        public IActionResult Delete(Customer cust)
        {
            foreach (var n in _db.Appointments.Where(custo => custo.IdCustomer == cust.IdCustomer).ToArray())
                _db.Appointments.Remove(n);
            /*
            var app = from a in _db.Appointments.ToList() where a.IdCustomer == cust.IdCustomer select a;
            if(app.Count() != 0) // ou app.Any()
            {
                _db.Appointments.RemoveRange(app);
            }
            */
            _db.Customers.Remove(cust);
            _db.SaveChanges();

            TempData["success"] = "Le client a bien été supprimé";

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - agendaEFD</title>
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/agendaEFD.styles.css" asp-append-version="true" />
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Courtier-Agenda</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Broker" asp-action="Index">Courtiers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="Index">Rendez-vous</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if(TempData["success"] != null)
            {
                <div class="alert alert-dismissible alert-success">
                  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                  @TempData["success"]</div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Courtier-Agenda - <a asp-area="" asp-controller="Home" asp-action="Privacy">CGV</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>