Models/Broker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using agendaEFD.Data;

namespace agendaEFD.Models
{
    public partial class Broker
    {
        public Broker()
        {
            Appointments = new HashSet<Appointment>();
        }

        [Key]
        public int IdBroker { get; set; }

        [Required(ErrorMessage = "Le champs Nom doit etre rempli.")]
        [Display(Name = "Votre nom de famille")]
        public string Lastname { get; set; } = null!;

        [Required(ErrorMessage = "Le champs Prénom doit etre rempli.")]
        [Display(Name = "Votre prénom")]
        public string Firstname { get; set; } = null!;

        [Required(ErrorMessage = "Le champs Email doit etre rempli.")]
        [Display(Name = "Votre adresse email")]
        [EmailAddress(ErrorMessage = "Vous n'avez pas entré une adresse email.")]
        public string Mail { get; set; } = null!;

        [Required(ErrorMessage = "Le champs Numéro de téléphone doit etre rempli.")]
        [Display(Name = "Votre numéro de téléphone")]
        [MinLength(10, ErrorMessage = "Le numéro doit comporter au moins 10 chiffres.")]
        [MaxLength(10, ErrorMessage = "Le numéro doit comporter maximum 10 chiffres.")]
        public string PhoneNumber { get; set; } = null!;

        public virtual ICollection<Appointment> Appointments { get; set; }

    }
}

Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using agendaEFD.Data;
using agendaEFD.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace agendaEFD.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly agendaContext _db;

        public AppointmentController(agendaContext db)
        {
            _db = db;
        }
    
        public IActionResult Index()
        {
            IEnumerable<Appointment> Appointments = _db.Appointments;
            IEnumerable<Broker> Brokers = _db.Brokers;
            IEnumerable<Customer> Customers = _db.Customers;

            /*
           "SELECT appointments.idAppointment, appointments.dateHour, appointments.subject, brokers.firstname, " +
               "brokers.lastname, customers.firstname, customers.lastname FROM appointments " +
               "INNER JOIN brokers ON brokers.idBroker = appointments.idBroker " +
               "INNER JOIN customers ON customers.idCustomer = appointments.idCustomer" */

            // On aurait même pu faire "from a in _db.Appointments" directement au lieu d’utiliser les IEnumerable

            /*
            string connectionString;
            SqlConnection cnn;

            connectionString = @"Server=DESKTOP-6IV8GIO\\SQLEXPRESS;Database=agendaLogin;Trusted_Connection=True;MultipleActiveResultSets=true";

            cnn = new SqlConnection(connectionString);
            cnn.Open();

            SqlCommand command;
            SqlDataReader dataReader;
            string sql, Output = "";

            sql = "SELECT appointments.idAppointment, appointments.dateHour, appointments.subject, brokers.firstname, " +
               "brokers.lastname, customers.firstname, customers.lastname FROM appointments " +
               "INNER JOIN brokers ON brokers.idBroker = appointments.idBroker " +
               "INNER JOIN customers ON customers.idCustomer = appointments.idCustomer";


            command = new SqlCommand(sql);

            dataReader = command.ExecuteReader();

            List<string> AppointmentViewModel = new List<string>();

            while (dataReader.Read())
            {
                AppointmentViewModel.Add(dataReader.GetValue(0) + "");
                AppointmentViewModel.Add(dataReader.GetValue(1) + "");
                AppointmentViewModel.Add(dataReader.GetValue(2) + "");
                AppointmentViewModel.Add(dataReader.GetValue(3) + "");
                AppointmentViewModel.Add(dataReader.GetValue(4) + "");
                AppointmentViewModel.Add(dataReader.GetValue(5) + "");
                AppointmentViewModel.Add(dataReader.GetValue(6) + "");
            }


            cnn.Close();
            */

            IEnumerable<BrokerCustomerAppointment> AppointmentViewModel = from a in Appointments.ToList()
                                                                          join c in Customers.ToList() on a.IdCustomer equals c.IdCustomer
                                                                          join b in Brokers.ToList() on a.IdBroker equals b.IdBroker
                                                                          select new BrokerCustomerAppointment { AppointmentVm = a, CustomerVm = c, BrokerVm = b };

            return View(AppointmentViewModel);
        }



        public IActionResult Add(int? id)
        {
            if (id == null || id == 0)
            {
                ViewBag.Brokers = new SelectList(_db.Brokers, "IdBroker", "Lastname");
                ViewBag.Customers = new SelectList(_db.Customers, "IdCustomer", "Lastname");
                return View();
            }

            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            List<Broker> brokers = new List<Broker>();
            brokers.Add(broker);

            ViewBag.Brokers = new SelectList(brokers, "IdBroker", "Lastname");
            ViewBag.Customers = new SelectList(_db.Customers, "IdCustomer", "Lastname");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Appointment appoint)
        {

            //if (ModelState.IsValid)  On ne peut pas utiliser ModelState ici, pour verifier si tous les champs sont bien remplis
            //{
            
            if (appoint.IdBroker == 0)
            {
                TempData["success"] = "Erreur! Vous n'avez pas séléctionné un courtier !";

                return RedirectToAction("Index");
            }
            else if (appoint.IdCustomer == 0)
            {
                TempData["success"] = "Erreur! Vous n'avez pas séléctionné un client !";

                return RedirectToAction("Index");
            } else
            {
                _db.Appointments.Add(appoint);
                _db.SaveChanges();

                TempData["success"] = "Le rendez-vous a bien été ajouté";

                return RedirectToAction("Index");
            }

            
            //}

            // return View();
        }

        // code ci-dessous pas encore mis en place ----------------------------------
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var appoint = _db.Appointments.Find(id);

            if (appoint == null)
            {
                return NotFound();
            }

            /*
            IEnumerable<BrokerCustomerAppointment> AppointmentViewModel = from a in _db.Appointments
                      join c in _db.Customers on a.IdCustomer equals c.IdCustomer
                      join b in _db.Brokers on a.IdBroker equals b.IdBroker
                      where a.IdAppointment == id
                      select new BrokerCustomerAppointment { AppointmentVm = a, CustomerVm = c, BrokerVm = b };
            */

            // select and from clause in C#
            // ViewBag.Brokers = from b in _db.Brokers select b.Lastname;
            // ViewBag.Customers = from c in _db.Customers select c.Lastname; 

            // Where method in C#
            // var result = _db.Customers.Where(customer => customer.Firstname.StartsWith(id) );

            // ViewBag.DateHour = from a in _db.Appointments where a.IdAppointment == id select a.DateHour;
            // ViewBag.Subject = from a in _db.Appointments where a.IdAppointment == id select a.Subject;
            /* ViewData["subject"] = from a in _db.Appointments where a.IdAppointment == id select a.Subject;
             ViewData["datehour"] = from a in _db.Appointments where a.IdAppointment == id select a.DateHour; */

            ViewBag.Brokers = new SelectList(_db.Brokers, "IdBroker", "Lastname");
            ViewBag.Customers = new SelectList(_db.Customers, "IdCustomer", "Lastname");

            return View(appoint);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        // on peut aussi mettre "int Id" dans les parametres
        // et ca récupère l'id depuis le form sans avoir besoin d'ajouter un hidden dans le form
        public IActionResult Edit(Appointment appoint)
        {

            //if (ModelState.IsValid)
            //{
            if (appoint.IdBroker == 0)
            {
                TempData["success"] = "Erreur! Vous n'avez pas séléctionné un courtier !";

                return RedirectToAction("Index");
            }
            else if (appoint.IdCustomer == 0)
            {
                TempData["success"] = "Erreur! Vous n'avez pas séléctionné un client !";

                return RedirectToAction("Index");
            }
            else
            {
                _db.Appointments.Update(appoint);
                _db.SaveChanges();

                TempData["success"] = "Le rendez-vous a bien été modifié";

                return RedirectToAction("Index");
            }

            
            //}


            // return View();

        }

        // pour aller sur la view Delete 
        public IActionResult Delete(int? id)
        {
            // si j'ai pas d'id je retourne a la liste des articles
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var appoint = _db.Appointments.Find(id);

            if (appoint == null)
            {
                return NotFound();
            }
            /*
            TempData["brokers"] = from b in _db.Brokers where appoint.IdBroker == b.IdBroker select b.Lastname;
            TempData["customers"] = from c in _db.Customers where appoint.IdCustomer == c.IdCustomer select c.Lastname;*/
            ViewBag.Brokers = _db.Brokers.Find(appoint.IdBroker);
            ViewBag.Customers = _db.Customers.Find(appoint.IdCustomer);

            return View(appoint);
        }

        [HttpPost]
        public IActionResult Delete(Appointment appoint)
        {
            _db.Appointments.Remove(appoint);
            _db.SaveChanges();

            TempData["success"] = "Le rendez-vous a bien été supprimé";

            return RedirectToAction("Index");
        }
    }
}

Controllers/BrokerController.cs
using Microsoft.AspNetCore.Mvc;
using agendaEFD.Data;
using agendaEFD.Models;

namespace agendaEFD.Controllers
{
    public class BrokerController : Controller
    {
        private readonly agendaContext _db;

        public BrokerController(agendaContext db)
        {
            _db = db;
        }
        /*
        public IActionResult Index()
        {
            IEnumerable<Broker> Brokers = _db.Brokers;
            return View(Brokers);
        } */

        public IActionResult Index(string? searchString)
        {
            IEnumerable<Broker> Brokers = _db.Brokers;

            if (!String.IsNullOrEmpty(searchString))
            {
                var brokers = from c in _db.Brokers select c;
                brokers = brokers.Where(s => s.Lastname!.Contains(searchString) || s.Firstname.Contains(searchString));
                return View(brokers.ToList());
            }

            return View(Brokers);
        }

        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Broker broker)
        {
            if (broker.Firstname == broker.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }

            if (ModelState.IsValid)
            {

                _db.Brokers.Add(broker);
                _db.SaveChanges();

                TempData["success"] = "Le courtier a bien été ajouté";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id) 
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            return View(broker);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        // on peut aussi mettre "int Id" dans les parametres
        // et ca récupère l'id depuis le form sans avoir besoin d'ajouter un hidden dans le form
        public IActionResult Edit(Broker broker) 
        {
            if (broker.Firstname == broker.Lastname)
            {
                ModelState.AddModelError("NotEquals", "le champs prénom doit etre différent du nom de famille");
            }

            // broker.IdBroker = id;

            if (ModelState.IsValid)
            {


                _db.Brokers.Update(broker);
                _db.SaveChanges();

                TempData["success"] = "Le courtier a bien été modifié";

                return RedirectToAction("Index");
            }


            return View();

        }

        public IActionResult Profil(int? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            ViewBag.BrokerId = id;
            return View(broker);
        }

        // pour aller sur la view Delete 
        public IActionResult Delete(int? id)
        {
            // si j'ai pas d'id je retourne a la liste des articles
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            var broker = _db.Brokers.Find(id);

            if (broker == null)
            {
                return NotFound();
            }

            return View(broker);
        }

        [HttpPost]
        public IActionResult Delete(Broker broker)
        {
            foreach (var n in _db.Appointments.Where(brok => brok.IdBroker == broker.IdBroker).ToArray())
                _db.Appointments.Remove(n);
            /*
            var app = from a in _db.Appointments.ToList() where a.IdBroker == broker.IdBroker select a;
            if(app.Count() != 0) // ou app.Any()
            {
                _db.Appointments.RemoveRange(app);
            }
            */

            _db.Brokers.Remove(broker);
            
            _db.SaveChanges();

            TempData["success"] = "Le courtier a bien été supprimé";

            return RedirectToAction("Index");
        }
    }
}

Views/Broker/Add.cshtml
@model Broker
@{
    ViewData["Title"] = "Ajouter un Courtier";
}

<div class="m-5 d-flex justify-content-between">
    <h2> Ajouter un courtier </h2>
</div>

<div asp-validation-summary="All"></div> 

<form method="post" style="width:75%;margin:auto;">
   <fieldset>
    <div class="mb-3">
        <label asp-for="Lastname"></label>
        <input asp-for="Lastname" class="form-control" /> 
        <span asp-validation-for="Lastname" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Firstname"></label>
        <input asp-for="Firstname" class="form-control" />
        <span asp-validation-for="Firstname" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Mail"></label>
        <input asp-for="Mail" class="form-control" />
        <span asp-validation-for="Mail" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="text-center m-4 p-2">
        <button class="btn btn-secondary" style="width:100px">Ajouter</button>
        <a class="btn btn-secondary" style="width:100px" asp-controller="Broker" asp-action="Index">Revenir</a>
    </div>
   </fieldset>
</form>

@section Scripts {
      @{
          <partial name="_ValidationScriptsPartial"></partial>
      }
}

Views/Broker/Delete.cshtml
@model Broker
@{
    ViewData["Title"] = "Supprimer un Courtier";
}




<div class="m-5 d-flex justify-content-between">
    <h2> Voulez-vous vraiment supprimer le courtier ? </h2>
</div>

 
<form method="post" style="width:75%;margin:auto;">
   <fieldset>
    <div class="mb-3">
        <label asp-for="Lastname"></label>
        <input asp-for="IdBroker" hidden />
        <input asp-for="Lastname" class="form-control" disabled /> 
    </div>
    <div class="mb-3">
        <label asp-for="Firstname"></label>
        <input asp-for="Firstname" class="form-control" disabled />
    </div>
    <div class="mb-3">
        <label asp-for="Mail"></label>
        <input asp-for="Mail" class="form-control" disabled />
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" disabled />
    </div>
    <div class="text-center m-4 p-2">
        <button class="btn btn-secondary" style="width:100px">Supprimer</button>
        <a class="btn btn-secondary" style="width:100px" asp-controller="Broker" asp-action="Index">Revenir</a>
    </div>
   </fieldset>
</form>

Views/Broker/Edit.cshtml
@model Broker
@{
    ViewData["Title"] = "Modifier un Courtier";
}




<div class="m-5 d-flex justify-content-between">
    <h2> Modifier un courtier </h2>
</div>

<div asp-validation-summary="All"></div> 
 
<form method="post" style="width:75%;margin:auto;">
   <fieldset>
    <div class="mb-3">
        <label asp-for="Lastname"></label>
        <input asp-for="Lastname" class="form-control" /> 
        <input asp-for="IdBroker" hidden />
        <span asp-validation-for="Lastname" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Firstname"></label>
        <input asp-for="Firstname" class="form-control" />
        <span asp-validation-for="Firstname" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Mail"></label>
        <input asp-for="Mail" class="form-control" />
        <span asp-validation-for="Mail" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="text-center m-4 p-2">
        <button class="btn btn-secondary" style="width:100px">Modifier</button>
        <a class="btn btn-secondary" style="width:100px" asp-controller="Broker" asp-action="Index">Revenir</a>
    </div>
   </fieldset>
</form>


@section Scripts {
      @{
          <partial name="_ValidationScriptsPartial"></partial>
      }
}

Views/Broker/Index.cshtml
@model IEnumerable<Broker>
@{
    ViewData["Title"] = "Liste des Courtiers";
}


<div class="m-5 d-flex justify-content-between">
<h2>Liste des courtiers</h2>
    <a class="btn btn-primary" asp-controller="Broker" asp-action="Add"><i class="bi bi-plus-square"></i> Ajouter Courtier</a>
</div>

<form method="get">
    <div class="mb-3">
        <input type="text" placeholder="Chercher un courtier" name="searchString" />
        <input type="submit" value="Filtrer" />
    </div>
</form>

<table class="table table-hover" style="width:100%">
    <thead>
        <tr class="table-dark">
            <th scope="col">#id</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Email</th>
            <th scope="col">RDV</th>
            <th scope="col">Voir</th>
            <th scope="col">Edition</th>
            <th scope="col">Suppression</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var broker in Model)
        {
            <tr class="table-warning">
                <th scope="row">@broker.IdBroker</th>
                <td> @broker.Lastname</td>
                <td> @broker.Firstname</td>
                <td> @broker.Mail</td>
                <td>
                    <a class="btn btn-primary"
                    asp-controller="Appointment"
                    asp-action="Add"
                    asp-route-id="@broker.IdBroker">RDV</a>
                </td>
                <td>
                    <a class="btn btn-primary"
                    asp-controller="Broker"
                    asp-action="Profil"
                    asp-route-id="@broker.IdBroker">Voir</a>
                </td>
                <td>
                    <a class="btn btn-primary"
                    asp-controller="Broker"
                    asp-action="Edit"
                    asp-route-id="@broker.IdBroker">Modifier</a>
                </td>
                <td>
                    <a class="btn btn-danger"
                    asp-controller="Broker"
                    asp-action="Delete"
                    asp-route-id="@broker.IdBroker">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Broker/Profil.cshtml
@model Broker
@{
    ViewData["Title"] = "Profile du Courtier";
}

<div class="m-5 d-flex justify-content-between">
    <a class="btn btn-primary" asp-controller="Broker" asp-action="Edit" asp-route-id="@ViewBag.BrokerId"><i class="bi bi-plus-square"></i> Modifier le Courtier</a>
</div>


<div class="m-5 d-flex justify-content-between">
    <h2> Profile du courtier </h2>
</div>

<div asp-validation-summary="All"></div> 
 
<form method="post" style="width:75%;margin:auto;">
   <fieldset>
    <div class="mb-3">
        <label asp-for="Lastname"></label>
        <input asp-for="Lastname" class="form-control" disabled /> 
    </div>
    <div class="mb-3">
        <label asp-for="Firstname"></label>
        <input asp-for="Firstname" class="form-control" disabled />
    </div>
    <div class="mb-3">
        <label asp-for="Mail"></label>
        <input asp-for="Mail" class="form-control" disabled />
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" disabled />
    </div>
    <div class="text-center m-4 p-2">
        <a class="btn btn-secondary" style="width:100px" asp-controller="Broker" asp-action="Index">Revenir</a>
    </div>
   </fieldset>
</form>


@section Scripts {
      @{
          <partial name="_ValidationScriptsPartial"></partial>
      }
}